/** TanStack Query keys, one place so mutations can invalidate the right lists. */
export const qk = {
  me: ["me"] as const,
  demoAccounts: ["demo-accounts"] as const,
  tasks: ["tasks"] as const,
  notifications: ["notifications"] as const,
  devStatus: ["dev-status"] as const,
  now: ["now"] as const,
  meetings: ["meetings"] as const,
  meeting: (id: string) => ["meeting", id] as const,
  meetingRoles: (id: string) => ["meeting-roles", id] as const,
  agendaOutline: (id: string) => ["agenda-outline", id] as const,
  myBoard: (id: string) => ["my-board", id] as const,
  roleTemplates: ["role-templates"] as const,
  projects: ["projects"] as const,
  members: ["members"] as const,
  audit: (f: unknown) => ["audit", f] as const,
  prefs: ["notif-prefs"] as const,
  club: ["club-settings"] as const,
  profile: (id: string) => ["profile", id] as const,
  impact: (id: string) => ["impact", id] as const,
  meetingTypes: ["meeting-types"] as const,
  reports: (id: string) => ["reports", id] as const,
  recurring: ["recurring"] as const,
  openForMe: ["open-for-me"] as const,
  pendingWithdrawals: ["pending-withdrawals"] as const,
  verifyQueue: ["verify-queue"] as const,
  myCompletions: ["my-completions"] as const,
  votes: ["votes"] as const,
  vote: (id: string) => ["vote", id] as const,
  positions: ["positions"] as const,
};
